### ISSUE TITLE
Éviter un fork

### ISSUE THREAD

**Issue by hippalectryon-0** [mmouterde/regles-ultimate-fr#26]
Origine: https://github.com/sallesma/timeout-ultimate/issues/7#issuecomment-1179136602

Problème : on a chacun de notre côté fait une traduction des annotations. En regardant ta version, je trouve que tes traductions sont de meilleure qualité, mais malheureusement on a des points de divergences assez fortes qui m'empêchent de simplement remplacer ma version par la tienne. D'où cette issue pour essayer de régler le problème et éviter d'avoir deux versions des annotations en circulation.

Ce qui me dérange :
* Je remarque que tu as "francisé" des termes qui ne le sont pas dans la traduction officielle des règles (ex: turnover > revirement). De plus, de mon expérience personnelle, personne n'utilise ces termes français.
* Je remarque une certaine liberté sur les traductions (ex: "Providing evidence to support a call" > "Expliquer leur point de vue clairement et brièvement"). Bien que cela ne change pas le message global, je ne suis pas sûr de comprendre ce choix, car je ne vois pas de défaut à une traduction plus proche de l'original.
* Je remarque que tu as supprimé des débuts de lignes Note/Result/Why/What/..., pour parfois les remplacer par des points markdown. Bien que le formattage qui en résulte soit plus plaisant, je pense qu'on perd significativement en clareté.
* (plus mineur) Je remarque à certains endroits ce qui me semble être des erreurs de traduction, ex dans "transgression délibérée ou flagrante des règles (1.2.1)", "Captains may choose to allow the receiver to claim a goal, **instead of** the receiver gaining possession and moving to the goal line." est devenu "Les capitaines peuvent choisir d'accepter le point **ou que** le receptionneur gagne la possession *et reprenne depuis la ligne de la zone d'en-but."

Quel est ton point de vue ?

PS: En lançant ton repo (je connais mal la techno que tu utilises), je m'aperçois que ton repo construit un site web pour les règles FR. Je tenais juste à t'informer que je suis aussi en train d'adapter mon appli de règles en version web (à venir sur https://wfdfrules.com/) pour toutes les langues de l'appli (donc y compris fr). Je n'ai rien contre une duplication des sites de règles, mais je préfère te le dire au cas où ;)

**Comment by mmouterde** [comment]
Bonjour, 

1- Je comprend la gène liée à la traduction de _turnover_ par _revirement_. Je ne suis pas surpris. C'est, en effet, pas utilisé sur les terrains en France. Je tiens cette traduction de nos cousins québécois. Il me semble qu'il s'agit de la seule liberté de traduction sur un mot clé que je me suis laisser aller à faire. C'est d'ailleurs pour cela que je répète le plus souvent le terme anglophone après. 

Dans la mesure où il s'agit d'une traduction d'un document officiel, je ne tiens pas absolument à y faire des propositions de changement comme celle-ci. Je suis pret à y renoncer pour cette traduction. Néanmoins je pense que c'est une proposition intéressante pour laquelle j'aimerai militer. Le fait que ce terme ne soit pas traduit du tout dans les règles françaises me dérange un peu : il y a bien un mot équivalent dans notre langue contrairement au _brick_ par exemple (?!).

2- Ici j'ai simplement repris l'intitulé de la règle 1.3.4 dont il est question. C'est en effet une initiative de ma part qui éloigne de la traduction exacte. La règle 1.3.4 ne faisant pas mention des termes utilisés dans le titre. Dans les annotations, le titre d'une section reprend souvent une partie du texte de la règle qu'elle précise, ce n'est pas le cas ici.

3- J'ai supprimé la structure Note,Result,Why,What. C'est pourtant une structure que j'ai beaucoup aimé à l'origine. La structure  Situation>Résolution>Explication est une très bonne idée. Au début de ma traduction, je l'avais conservé. Mais plus on avance dans le document, plus l'usage de cette structure devient bordélique :
  - le sens initialement associé au Note/Extra/Result/Why change voir s'inverse, il n'est ni constant ni cohérent. 
  - Il y a plusieurs cas où un Note/Extra ne fait pas du tout référence à la situation What qui précède, c'est juste utilisé comme artifice pour y caler une précision supplémentaire. Même le regroupement en paragraphe ou bullet points peut être discutable.
Pour ces raisons, j'ai préféré supprimer le _typage_ des paragraphes. Une autre solution aurait été de corriger et redonner la constance/cohérence, mais j'ai trouvé cela plus intrusif dans un travail de traduction. J'ai préféré supprimer la structure que la changer.

2 et 4- Des erreurs de traduction, il y en a forcément, toute relecture est la bienvenue, je préfère un travail collaboratif. Pour autant, je préfererais qu'on créé une issue pour chaque erreur de traduction (ou type d'erreur). Les PR sont aussi les bienvenues !

Merci de m'avoir prévenu, pas de problème pour moi non plus, plus on a de supports de communication sur les règles plus elles seront connues. Je tient juste à ce que le travail de chacun soit respecté : remerciement, liens, contributions plutôt que appropriation et pillage.

**Comment by hippalectryon-0** [comment]
1. Pour le cas de "revirement" : que penses-tu de demander l'avis de la fédé ?
3. Je comprends mieux pourquoi tu as fait ainsi. Cependant, le retrait de ces termes est problématique pour toutes les utilisations qui acceptent des données brutes et non du Markdown (par exemple mon appli :P). De plus les autres langues qui ont traduit les annotations (Italien et Allemand) ont conservé la structure. À titre personnel, je n'ai pas vu d'inconvénient à avoir dans Note/Extra des précisions non liées au What précédent, je ne me rappelle pas une situation où ça mène à confusion, à quoi pensais-tu en particulier ? Par ailleurs, ne serait-il pas possible de conserver les Note/... dans la traduction, quitte à ce que sur ton site tu les remplaces automatiquement par du markdown ?
4. Oui c'est ce que je me disais, je n'étais juste pas sûr si c'était accidentel ou intentionnel ;)

>  Je tient juste à ce que le travail de chacun soit respecté : remerciement, liens, contributions plutôt que appropriation et pillage.

Bien entendu ! Mais ça serait encore plus simple si tu rajoutes une license ;)

Pour conclure : a titre personnel, je n'ai pas d'opinion forte sur la forme que "devrait" prendre les règles, mon travail principal est de créer des outils pour les rendre accessibles (appli, site web, quiz). Ma principale inquiétude est par rapport aux disparitions des sections Extra/..., qui rendraient les règles moins lisibles en français sur la version actuelle sans Markdown (https://wfdfrules.com/rules). Au global, ta traduction est clairement de meilleure qualité que la mienne (fait rapidement avec DeepL + relecture à la main), donc j'aimerais bien l'utiliser. Mon but n'est pas du tout de critiquer le travail accompli !

**Comment by sallesma** [comment]
Je pense que si on arrive à converger vers une traduction fidèle des annotations, on peut ensuite la proposer dans le format qu'on veut

- un format 100% identique à celui de la WFDF pour que la FFDF puisse l'adopter comme traduction officielle si elle le souhaite
- un format plus facile à traiter au niveau informatique (j'ai envie de dire peu importe, même si c'est vrai que json c'est bien) pour que chacun (bot mattermost, timeout ultimate, wfdfrules, etc) puisse l'utiliser en respectant sa licence
